name: Deploy React to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'  # You can specify your Node.js version here

    - name: Install dependencies
      run: ../.devcontainer/React/install.sh
      working-directory: ./frontend

    - name: Build
      run: npm run build
      working-directory: ./frontend

    - name: ShowOutput
      run: ls -laR dist
      working-directory: ./frontend

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5  # Check for the latest version
      with:
        branch: gh-pages  # Deployment branch
        folder: ./frontend/dist  # Folder where your build is located
        token: ${{ secrets.GITHUB_TOKEN }}  # GitHub will automatically create this secret for you
