name: Deploy Python App to Azure Functions

on:
  push:
    branches:
      - main  # replace with your default branch if not 'main'

env:
  AZURE_FUNCTIONAPP_NAME: 'sentimentabot'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './backend'       # set this to the path to your function app project, defaults to the repository root
  PYTHON_VERSION: '3.12'                     # set this to the python version to use (e.g. '3.6', '3.7', '3.8')
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true
  

# Run the following commands in an Azure Cloud Shell terminal to get the values for the two secrets
# az account set --subscription DemoAndPortfolioProjects
# $resourceGroupId = az group show --name "Sentimentabot" --query "id" --output tsv
# az ad sp create-for-rbac --name "your-service-principal-name" --role contributor --scopes $resourceGroupId --sdk-auth
# az webapp deployment list-publishing-profiles --name sentimentabot --resource-group Sentimentabot --query "[?publishMethod=='MSDeploy'].{profileName:profileName,publishUrl:publishUrl,userName:userName,userPWD:userPWD}" --output json
# az webapp deployment list-publishing-profiles --name sentimentabot --resource-group Sentimentabot --subscription DemoAndPortfolioProjects

