name: Deploy Python App to Azure Functions

on:
  push:
    branches:
      - main  # replace with your default branch if not 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./backend

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Validate Secret is XML
      run: |
        echo "${{ secrets.AZURE_PUBLISH_PROFILE }}" > secret.xml
        python -c "import xml.etree.ElementTree as ET; ET.parse('secret.xml')"
      
    - name: Deploy to Azure Functions
      uses: azure/functions-action@v1.5.1
      with:
        app-name: sentimentabot
        package: ./backend
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}


# Run the following commands in an Azure Cloud Shell terminal to get the values for the two secrets
# az account set --subscription DemoAndPortfolioProjects
# $resourceGroupId = az group show --name "Sentimentabot" --query "id" --output tsv
# az ad sp create-for-rbac --name "your-service-principal-name" --role contributor --scopes $resourceGroupId --sdk-auth
# az webapp deployment list-publishing-profiles --name sentimentabot --resource-group Sentimentabot --query "[?publishMethod=='MSDeploy'].{profileName:profileName,publishUrl:publishUrl,userName:userName,userPWD:userPWD}" --output json
az webapp deployment list-publishing-profiles --name sentimentabot --resource-group Sentimentabot --subscription DemoAndPortfolioProjects

