name: Deploy Python App to Azure Functions

on:
  push:
    branches:
      - main  # replace with your default branch if not 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # replace with your desired version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Functions
      uses: azure/functions-action@v1
      with:
        app-name: YourFunctionAppName  # replace with your Function App name
        package: ./
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}

